upstream host_1 {
    zone host_1 64k;
    server 127.0.0.1:8080;
}

server {
    listen 80;
    server_name test.example.com;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    http2 on;
    server_name test.example.com;
    status_zone host_1;
    ssl_certificate     $acme_cert_web;
    ssl_certificate_key $acme_cert_key_web;
    location / {
        proxy_pass http://host_1;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
