#!/usr/bin/env bash
# Build the country -> CIDR dataset that backs geo blocking.
#
# Source: sapics/ip-location-db "geo-whois-asn-country" (public domain / CC0),
# which ships IP RANGES (start,end,country). Angie's `geo` directive needs CIDR
# notation (uniform for IPv4 + IPv6), so we summarize each range to CIDRs here.
#
# Output format (one per line): <ISO-3166-alpha-2>,<cidr>
# Run at package build time; overwrites the committed dev fixture.
#
# Usage: scripts/build-geoip-data.sh [output.csv]
set -euo pipefail

OUT="${1:-backend/data/geoip-countries.csv}"
BASE="https://raw.githubusercontent.com/sapics/ip-location-db/main/geo-whois-asn-country"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

echo "Downloading country IP ranges (CC0, sapics/ip-location-db)…" >&2
curl -fsSL "$BASE/geo-whois-asn-country-ipv4.csv" -o "$TMP/ipv4.csv"
curl -fsSL "$BASE/geo-whois-asn-country-ipv6.csv" -o "$TMP/ipv6.csv"

echo "Summarizing ranges to CIDR…" >&2
python3 - "$TMP/ipv4.csv" "$TMP/ipv6.csv" > "$TMP/out.csv" <<'PY'
import csv, ipaddress, sys
print("# Country -> CIDR dataset for geo blocking (format: country_code,cidr).")
print("# Generated by scripts/build-geoip-data.sh from sapics/ip-location-db (CC0).")
for path in sys.argv[1:]:
    with open(path, newline="") as fh:
        for row in csv.reader(fh):
            if len(row) < 3:
                continue
            start, end, cc = row[0].strip(), row[1].strip(), row[2].strip().upper()
            if len(cc) != 2 or not cc.isalpha():
                continue
            try:
                for net in ipaddress.summarize_address_range(
                    ipaddress.ip_address(start), ipaddress.ip_address(end)
                ):
                    print(f"{cc},{net}")
            except ValueError:
                continue
PY

mkdir -p "$(dirname "$OUT")"
mv "$TMP/out.csv" "$OUT"
echo "Wrote $(grep -vc '^#' "$OUT") CIDR entries to $OUT" >&2
